-- 코드를 입력하세요
SELECT i1.FOOD_TYPE, i1.REST_ID, i1.REST_NAME, i1.FAVORITES
FROM REST_INFO i1 
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) as MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) i2
ON i1.FOOD_TYPE = i2.FOOD_TYPE
WHERE i1.FAVORITES = i2.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC