SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) m
on fi.FISH_TYPE = m.FISH_TYPE
AND fi.LENGTH = m.LENGTH
JOIN FISH_NAME_INFO fni
ON fi.FISH_TYPE = fni.FISH_TYPE
ORDER BY fi.ID