-- 코드를 작성해주세요
SELECT SUM(g.SCORE) as SCORE,e.EMP_NO, e.EMP_NAME,e.POSITION,e.EMAIL
FROM HR_DEPARTMENT d
join HR_EMPLOYEES e
on d.DEPT_ID = e.DEPT_ID
join HR_GRADE g
on e.EMP_NO = g.EMP_NO
WHERE g.YEAR=2022
GROUP BY e.EMP_NO
ORDER BY SCORE DESC
LIMIT 1